[project]
name = "loveable-clone"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langgraph>=1.0.9",
    "pathlib>=1.0.1",
]
